name: Todo Application
on: 
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Code Chenckout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Project
        run: mvn clean install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create AWS Lambda Function
        run: |
          aws lambda create-function --function-name LambdaHandler --runtime java17 --handler com.example.todoApplication.LambdaHandler::handleRequest --role arn:aws:iam::975050363417:role/test-user-2 --zip-file fileb://target/todoApplication-0.0.1-SNAPSHOT.jar
        continue-on-error: true  
      - name: Update Lambda Function    
        run: aws lambda update-function-code --function-name LambdaHandler --s3-bucket deploy-bucket --s3-key lambda/todoApplication-0.0.1-SNAPSHOT.jar
