spring.application.name=todoApplication
spring.data.mongodb.uri=mongodb+srv://rainishu111:Nishu4044054@cluster0.23ebv.mongodb.net/todo_db?retryWrites=true&w=majority&appName=Cluster0
server.port=8080
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG
spring.main.allow-bean-definition-overriding=true

